server:
  port: 8080
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/new_schema?serverTimezone=UTC
    username: root
    password:
mybatis:
  mapper-locations: mapper/*.xml